build_from:
  amd64: ghcr.io/home-assistant/amd64-base:latest
  aarch64: ghcr.io/home-assistant/aarch64-base:latest
  armv7: ghcr.io/home-assistant/armv7-base:latest
labels:
  org.opencontainers.image.title: "LIFX Switch Bridge"
  org.opencontainers.image.description: "Exposes LIFX Switch relays and backlights via Photons Interactor + MQTT"
  org.opencontainers.image.source: "https://github.com/m7les/hassio-addons"
  org.opencontainers.image.licenses: "MIT"
